/* Configuration for adafhashmurm generated by Alire */
#ifndef ADAFHASHMURM_CONFIG_H
#define ADAFHASHMURM_CONFIG_H

#define CRATE_VERSION "3.0.0-dev"
#define CRATE_NAME "adafhashmurm"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "macports"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
